name: dev
pool: himanshu
trigger: none
stages:
  - stage: tfsec
    jobs:
      - job:
        steps:
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'init'
            backendServiceArm: 'nayaserviceconnection'
            backendAzureRmStorageAccountName: 'pipelinestorageaccount1'
            backendAzureRmContainerName: 'pipeline'
            backendAzureRmKey: 'vikrant.tfstate'
        - task: tfsec@1
          inputs:
            version: 'v1.26.0'
  - stage: initandplan
    dependsOn: tfsec
    jobs:
      - job: initandplan
        steps:
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'init'
            backendServiceArm: 'nayaserviceconnection'
            backendAzureRmStorageAccountName: 'pipelinestorageaccount1'
            backendAzureRmContainerName: 'pipeline'
            backendAzureRmKey: 'vikrant.tfstate'
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'plan'
            environmentServiceNameAzureRM: 'nayaserviceconnection'
  - stage: manual
    dependsOn: initandplan
    jobs:
      - job: manual
        pool: server
        steps:
        - task: ManualValidation@1
          inputs:
            notifyUsers: 'vikrantp218@gmail.com.com'
            approvers: 'vkrant@prashantextramarkgmail.onmicrosoft.com'
   
  - stage: apply
    dependsOn:  manual
    jobs:
      - job: init
        steps: 
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'init'
            backendServiceArm: 'nayaserviceconnection'
            backendAzureRmStorageAccountName: 'pipelinestorageaccount1'
            backendAzureRmContainerName: 'pipeline'
            backendAzureRmKey: 'vikrant.tfstate'

        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'apply'
            commandOptions: '-auto-approve'
            environmentServiceNameAzureRM: 'nayaserviceconnection'